name: cp index.html 404.html -f
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'copy.txt'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: file copy
        run: cp index.html 404.html -f
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cp command
